# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7wofKPJv4gljXXwXRdQP0DH6MJqr00N
"""

from google.colab import files
uploaded = files.upload()

import os
os.listdir()

import pandas as pd

df = pd.read_excel('stc TV Data Set_T1 (1).xlsb', engine='pyxlsb')

df.head()

!pip install pyxlsb

import pandas as pd

df = pd.read_excel('stc TV Data Set_T1 (1).xlsb', engine='pyxlsb')

df.head()

import pandas as pd

df = pd.read_excel('stc TV Data Set_T1.xlsx')

df.head()

# 1. شكل البيانات (عدد الصفوف والأعمدة)
print("شكل البيانات (صفوف، أعمدة):", df.shape)

# 2. التحقق من القيم الفارغة
print("\nعدد القيم الفارغة في كل عمود:")
print(df.isnull().sum())

# 3. وصف القيم الرقمية (متوسط، انحراف معياري، عظمى، صغرى)
print("\nإحصائيات القيم الرقمية:")
print(df.describe())

df['program_desc'].fillna('غير متوفر', inplace=True)

print(df['program_class'].value_counts())

print(df['hd'].value_counts())

df.groupby(['program_class', 'hd']).size().unstack()

df.groupby(['program_class', 'hd'])['duration_seconds'].agg(['mean', 'std']).round(2)